version: '3.9'

services:
    postgres-db:
        image: 'postgres:latest'
        ports:
            - 15432:5432
        environment:
            - POSTGRES_USER=testuser
            - POSTGRES_PASSWORD=testpassword
        networks:
            sql2o-network:

    db2-db:
        #privileged: true
        volumes:
            - type: volume
              source: db2-db
              target: /database
        cap_add:
            - IPC_LOCK
            - IPC_OWNER
        ipc: host
        image: 'icr.io/db2_community/db2'
        ports:
            - 50000:50000
        environment:
            - LICENSE=accept
            - DB2INSTANCE=db2inst1
            - DB2INST1_PASSWORD=testpassword
            - DBNAME=testdb
            - BLU=false
            - ENABLE_ORACLE_COMPATIBILITY=false
            - UPDATEAVAIL=NO
            - TO_CREATE_SAMPLEDB=true
            - REPODB=false
            - IS_OSXFS=false
            - PERSISTENT_HOME=false
            - HADR_ENABLED=false
            - ETCD_ENDPOINT=
            - ETCD_USERNAME=
            - ETCD_PASSWORD=
        networks:
            sql2o-network:

volumes:
    db2-db:

networks:
    sql2o-network:
        name: sql2o-network
        driver: bridge