package org.sql2o.extensions.derby;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.sql2o.Connection;
import org.sql2o.Sql2o;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * Mapping by the label an alias was given, where derby folds an unquoted one to upper case.
 *
 * <p>sql2o reads {@code ResultSet.getColumnLabel()}, so {@code select id, val theVal} maps onto a property called
 * {@code theVal}. On most of the databases here the label comes back exactly as the query spelled it, but derby folds an
 * unquoted identifier to upper case and answers {@code THEVAL}. The mapping still works, because name derivation is case
 * insensitive and {@code THEVAL} is the same name as {@code theVal} in that sense.
 *
 * <p>Quoting the alias is what makes it come back as written, and both spellings are asserted here rather than only the
 * one that happens to work, since a caller whose alias is written in a case the property is not has to know which of the
 * two it is relying on.
 */
public class DerbyColumnLabelTest {

    private static final String URL = "jdbc:derby:memory:columnlabeldb;create=true";

    private static final String TABLE = "DERBYCOLUMNLABEL";

    private static Sql2o sql2o;

    @BeforeAll
    public static void openSql2o() {
        sql2o = new Sql2o(URL, null, null);

        dropTheTable();

        try (Connection connection = sql2o.open()) {
            connection.createQuery("create table " + TABLE
                    + " (id integer generated by default as identity primary key, val varchar(50))").executeUpdate();

            String insertSql = "insert into " + TABLE + "(val) values (:val)";
            for (String value : List.of("something", "something else", "something third")) {
                connection.createQuery(insertSql).addParameter("val", value).executeUpdate();
            }
        }
    }

    @AfterAll
    public static void dropTheTable() {
        try (Connection connection = sql2o.open()) {
            connection.createQuery("drop table " + TABLE).executeUpdate();
        } catch (RuntimeException ignored) {
            // The table is not there, which is exactly the state this was called in.
        }
    }

    /** An unquoted alias, which derby folds to upper case and sql2o matches case insensitively. */
    @Test
    public void anUnquotedAliasMapsOntoThePropertyItNames() {
        try (Connection connection = sql2o.open()) {
            List<Issue9Pojo> pojos = connection
                    .createQuery("select id, val theVal from " + TABLE)
                    .executeAndFetch(Issue9Pojo.class);

            assertEquals(3, pojos.size());
            assertEquals("something", pojos.get(0).theVal);
        }
    }

    /** The same alias quoted, which is how a caller asks derby to leave the spelling alone. */
    @Test
    public void aQuotedAliasComesBackAsItWasWrittenAndMapsTheSameWay() {
        try (Connection connection = sql2o.open()) {
            List<Issue9Pojo> pojos = connection
                    .createQuery("select id, val as \"theVal\" from " + TABLE)
                    .executeAndFetch(Issue9Pojo.class);

            assertEquals(3, pojos.size());
            assertEquals("something", pojos.get(0).theVal);
        }
    }

    public static class Issue9Pojo {
        public int id;
        public String theVal;
    }
}