package org.sql2o.extensions.derby;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.sql2o.Connection;
import org.sql2o.Sql2o;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Generated keys, where derby behaves like h2 and not like hsqldb: only the last one of several comes back.
 *
 * <p>There is a class of this in {@code Sql2oTest} of core for the databases that keep all of them, and one in the hsqldb
 * extension for hsqldb, which hands back every key for a batch and for a multi row insert alike. Derby is measured here
 * because it is the other kind of database: a batch of three answers with one key and a multi row insert answers with one
 * key that is null. Both are asserted here rather than left to the weaker assertion in core, since a test that fits h2
 * says nothing about derby and one that fits hsqldb fails on it.
 */
public class DerbyGeneratedKeysTest {

    private static final String URL = "jdbc:derby:memory:generatedkeysdb;create=true";

    private static final String TABLE = "DERBYGENERATEDKEYS";

    private static Sql2o sql2o;

    @BeforeAll
    public static void openSql2o() {
        sql2o = new Sql2o(URL, null, null);

        dropTheTable();

        try (Connection connection = sql2o.open()) {
            connection.createQuery("create table " + TABLE
                    + " (id integer generated by default as identity primary key, val_col varchar(20))").executeUpdate();
        }
    }

    @AfterAll
    public static void dropTheTable() {
        try (Connection connection = sql2o.open()) {
            connection.createQuery("drop table " + TABLE).executeUpdate();
        } catch (RuntimeException ignored) {
            // The table is not there, which is exactly the state this was called in.
        }
    }

    private static void clear() {
        try (Connection connection = sql2o.open()) {
            connection.createQuery("delete from " + TABLE).executeUpdate();
        }
    }

    /** One insert of several rows written with a comma, and the keys it hands back. */
    @Test
    public void anInsertOfSeveralRowsHandsBackOneKey() {
        clear();

        Object[] keys;
        try (Connection connection = sql2o.open()) {
            keys = connection
                    .createQuery("insert into " + TABLE + "(val_col) values ('a val'), ('another val'), ('a third')", true)
                    .executeUpdate()
                    .getKeys();
        }

        assertNotNull(keys);
        assertEqualsLength(1, keys.length);
        // And the one it does hand back is null, which is worth knowing before somebody reads a key out of it.
        assertEquals(null, keys[0]);
    }

    /** And the same for a batch, which is where h2 loses all but the last as well. */
    @Test
    public void aBatchHandsBackOneKey() {
        clear();

        List<String> vals = new ArrayList<>(List.of("something1", "something2", "something3"));

        List<Integer> keys;
        try (Connection connection = sql2o.open()) {
            var query = connection.createQuery("insert into " + TABLE + "(val_col) values(:val)", true);
            for (String val : vals) {
                query.addParameter("val", val);
                query.addToBatch();
            }
            keys = query.executeBatch().getKeys(Integer.class);
        }

        assertNotNull(keys);
        assertEqualsLength(1, keys.size());
    }

    /**
     * A single insert, which is the case every one of these databases does right, and which is what the identity column is
     * for. Without it the two above would only say that the keys are being lost somewhere.
     */
    @Test
    public void aSingleInsertHandsBackItsOwnKey() {
        clear();

        int key;
        try (Connection connection = sql2o.open()) {
            key = connection.createQuery("insert into " + TABLE + "(val_col) values(:val)")
                    .addParameter("val", "one row")
                    .executeUpdate()
                    .getKeys(Integer.class)
                    .get(0);
        }

        try (Connection connection = sql2o.open()) {
            // Not 1: the identity column counts every row the table has had, and the two tests above wrote six. The
            // delete in clear empties the table but does not reset the counter, which is what makes this a real key
            // rather than an accident of the order the tests run in.
            assertTrue(key > 1, "the key is one the table handed out earlier, not one it counts from: " + key);
            assertEquals(1, connection.createQuery("select count(*) from " + TABLE + " where id = " + key)
                    .executeScalar(Integer.class));
        }
    }

    private static void assertEqualsLength(int expected, int actual) {
        assertTrue(actual == expected,
                "expected " + expected + " keys but got " + actual);
    }
}