package org.sql2o.bytecode;

import org.sql2o.converters.Converter;
import org.sql2o.quirks.Quirks;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * What a generated class implements: one method that builds an object out of one row.
 *
 * <p>This is the contract between the generated bytecode and this extension, and it is deliberately narrower than
 * {@link org.sql2o.ResultSetHandler}. A handler is created per result set and is therefore tied to the quirks and the
 * converters of one query; a reader here is stateless and shared between every query of the same shape, which is why
 * both of those arrive as arguments instead of being held.
 *
 * <p>Nothing in a generated reader is allowed to keep state between calls. The object it builds lives in a local
 * variable, so the same instance may be called from several threads at once, and that is what lets the cache hold one
 * instance rather than a class per result set.
 */
public interface RowReader {

    /**
     * Builds one object out of the current row.
     *
     * @param resultSet  positioned on a row, which this method must not advance
     * @param quirks     reads the columns, and is not necessarily the quirks this reader was compiled against
     * @param converters one converter per column of the result set this reader was compiled for, with an entry of
     *                   null for a column that was compiled away, and an entry for every column otherwise
     * @return the built object, never null
     */
    Object build(ResultSet resultSet, Quirks quirks, Converter<?>[] converters) throws SQLException;
}