name: Deploy to maven central

on:
  release:
    types: [ "created" ]

jobs:
  build:
    name: Build, test and publish to Github Packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Docker Compose Action
        uses: isbang/compose-action@v1.5.1
      - name: Docker Compose Action
        uses: isbang/compose-action@v1.5.1
      - name: Set up JDK 17 and Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: publish to maven central
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
